### ISSUE TITLE
Not working mkv files 

### ISSUE THREAD

**Issue by thopDB** [hlsflow/hlsflow#2]
Not working above 200 mb and mkv files please solve

**Comment by tuhinpal** [comment]
It is an issue for lengthy files, those servers doesn't have a gpu included (or maybe we cannot take the advantages) so it needs much time to convert a video into 4 different quality, and one Github action instance's maximum lifetime is 6 hour.

**Comment by thopDB** [comment]
it's possible in hosting ? this hlsflow

**Comment by tuhinpal** [comment]
Yes, use this 👇

https://gist.github.com/tuhinpal/35d703ee8d1d76f40aa8015d9df5be6f

**Comment by thopDB** [comment]
If you have any video tutorial plz give me link

**Comment by tuhinpal** [comment]
https://raw.githubusercontent.com/hlsflow/hlsflow/main/process.gif

**Comment by thopDB** [comment]
Sir I'm asking about this : https://gist.github.com/tuhinpal/35d703ee8d1d76f40aa8015d9df5be6f
Tutorial for hosting
